# Copyright (c) 2026
# SPDX-License-Identifier: Apache-2.0

[package]
# This must be rustapp for now.
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = "CH32H417EVT V5F application: blink the on-board LED and print on USART8"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = "0.1.0"
log = "0.4.22"

[build-dependencies]
zephyr-build = "0.1.0"
